version: "3.9"

services:
  psql_bp:
    image: postgres:18-alpine
    container_name: psql_bp
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    healthcheck: # ✅ ตรวจสุขภาพก่อนให้ container อื่น connect ได้
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${BLUEPRINT_DB_USERNAME} -d ${BLUEPRINT_DB_DATABASE}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  psql_volume_bp:
